### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by GreywaterSoftware** [Scyllaly/hcaptcha#11]
Been trying to add validation to the controller files and it either just doesn't work at all or it gives my site a 500 error. please add more documentation

**Comment by GreywaterSoftware** [comment]
?

**Comment by RVxLab** [comment]
@roast247 Please add a code example of what you’re trying to do and the error you’re getting. 

Scyllaly is very inactive and it’s unlikely he’ll see this in the short term.

**Comment by GreywaterSoftware** [comment]
> @roast247 Please add a code example of what you’re trying to do and the error you’re getting.
> 
> Scyllaly is very inactive and it’s unlikely he’ll see this in the short term.

where do I put the validation script?

**Comment by RVxLab** [comment]
In the rules array of your validator or in the rules method of your form request. This is outlined in the docs as seen here: https://github.com/Scyllaly/hcaptcha#validation

For more information, please consult the Laravel documentation on validation: https://laravel.com/docs/9.x/validation#quick-writing-the-validation-logic

**Comment by GreywaterSoftware** [comment]
> In the rules array of your validator or in the rules method of your form request. This is outlined in the docs as seen here: https://github.com/Scyllaly/hcaptcha#validation
> 
> For more information, please consult the Laravel documentation on validation: https://laravel.com/docs/9.x/validation#quick-writing-the-validation-logic

So I added

`    protected function validatorLogin(Request $request)
 {
	$validate = Validator::make(Input::all(), [
	'h-captcha-response' => 'required|HCaptcha'
]);
    }`

to the logincontroller.php and I am able to still login without completing the captcha

**Comment by RVxLab** [comment]
Sounds like you didn’t add your hCaptcha key. Please carefully re-read the documentation.

**Comment by GreywaterSoftware** [comment]
> Sounds like you didn’t add your hCaptcha key. Please carefully re-read the documentation.

Sorry for a late reply, I have done basically everything, its just not being validated, I can login without completing the captcha. Still asking how to make it a required thing to do. I've been at this off and on for months, and it's probably a simple fix. please help

**Comment by RVxLab** [comment]
Without knowing what your code looks like I can't help you. Please provide your relevant `.env` entries, your config, your controller method and any other related code.

Additionally, if it helps, you can [check the documentation of my fork](https://github.com/RVxLab/hcaptcha#installation) which is 95% compatible with this repo and has better documentation.

To me it sounds like your captcha isn't being attempted to be verified, which sounds like misconfiguration.

**Comment by GreywaterSoftware** [comment]
> Without knowing what your code looks like I can't help you. Please provide your relevant `.env` entries, your config, your controller method and any other related code.
> 
> Additionally, if it helps, you can [check the documentation of my fork](https://github.com/RVxLab/hcaptcha#installation) which is 95% compatible with this repo and has better documentation.
> 
> To me it sounds like your captcha isn't being attempted to be verified, which sounds like misconfiguration.

Oh man! Finally! I found it! It was a file called "AuthenticatesUsers.php" hidden deep in the project I'm working on. Oh man! Thanks for your replies and help man!
