### ISSUE TITLE
Custom and default error message

### ISSUE THREAD

**Issue by Dezinger** [Scyllaly/hcaptcha#12]
1) In docs have error for message key. Maybe captcha => h_captcha?

```

'custom' => [
    'h-captcha-response' => [
        'required' => 'Please verify that you are not a robot.',
        'h_captcha' => 'Captcha error! try again later or contact site admin.',
    ],
],

```

2) Your should add default error message, otherwise if check will fail users see "validate.h_captcha" message.

**Comment by RVxLab** [comment]
This feature is available in [my fork](https://github.com/RVxLab/hcaptcha). The maintainer of this repo is inactive, don’t expect a reply anytime soon.

**Comment by Scyllaly** [comment]
@RVxLab sorry for late response, busy work recently

**Comment by Scyllaly** [comment]
@Dezinger fixed!
