### ISSUE TITLE
Config filename does not follow Laravel's pattern for config filenames. 

### ISSUE THREAD

**Issue by pricop** [Scyllaly/hcaptcha#16]
Hello,

Would you guys be open to change the config filename from config/HCaptcha.php to config/hcaptcha.php, so that it follows the Laravel's pattern for config filenames?

While this is not standardized, as Laravel doesn't enforce a specific filename, there's plenty of best practices recommendations, such as this one: https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions - and some of us are really trying to follow these patterns.

I can do a pull request if needed, and if you're open to this change, just let me know.

Thank you.

**Comment by Scyllaly** [comment]
hi @pricop, sorry for the late reply, busy works recently u know, kindly please do a pull request if you want. i will merge the code. thanks. 😄
