### ISSUE TITLE
Add support for recaptchacompat

### ISSUE THREAD

**Issue by edhelas** [Scyllaly/hcaptcha#20]
HCaptcha is having a few specific options that should be configurable, see the related documentation there https://docs.hcaptcha.com/configuration/
I am actually directly loading the script this way for the moment:

```xml
<script src="https://hcaptcha.com/1/api.js?recaptchacompat=off" async="" defer=""></script>
```

**Comment by Scyllaly** [comment]
hi @edhelas , please submit a PR so that i can merge and upgrade it as needed.
