### ISSUE TITLE
validation.h_captcha

### ISSUE THREAD

**Issue by radhikaagr18** [Scyllaly/hcaptcha#4]
How to solve this issue??

**Comment by r0073rr0r** [comment]
did u try to create validation.php file in lang folder for langages that u use? 
or if u have this file, just add this key and translate

**Comment by radhikaagr18** [comment]
Yeah even after that I get this issue!

**Comment by radhikaagr18** [comment]
'h-captcha-response' => [
            'required' => 'Please verify that you are not a robot.',
            'captcha' => 'Captcha error! try again later or contact site admin.',
        ],

**Comment by ngcoders** [comment]
The site key was invalid , fixing it resolved it . 

Maybe display the error-codes if in dev if success is false, if it fails else its hard to know what went wrong.

**Comment by Scyllaly** [comment]
@ngcoders roger that,let me have a check

**Comment by Samuelbdesouza** [comment]
I'm having this same error, but for me it's only occurring when the user submits the form without any other mandatory field, but with hcaptcha resolved and when re-submitting with the mandatory field filled in without reloading the page, hcaptcha returns this error !
