### ISSUE TITLE
Maintainer needed? - Fork available

### ISSUE THREAD

**Issue by RVxLab** [Scyllaly/hcaptcha#9]
I see this repo doesn't get a lot of commits, perhaps because of lack of time?

If you need a maintainer I'd be willing to give you a hand.

---

Due to Scyllaly being unresponsive I'm now maintaining [a fork](https://github.com/RVxLab/hcaptcha).

**Comment by tfevan** [comment]
No updates for Laravel 9 :(

**Comment by RVxLab** [comment]
If there’s no reply tomorrow I’ll publish my fork as a drop-in replacement and continue maintenance from there.

**Comment by tfevan** [comment]
> If there’s no reply tomorrow I’ll publish my fork as a drop-in replacement and continue maintenance from there.

Hope tomorrow I'll get it , this is the only outdated repository on my composer.json that need L9 support.

**Comment by RVxLab** [comment]
> > If there’s no reply tomorrow I’ll publish my fork as a drop-in replacement and continue maintenance from there.
> 
> Hope tomorrow I'll get it , this is the only outdated repository on my composer.json that need L9 support.

I just published my fork, simply replace `scyllaly/hcaptcha` with `rvxlab/hcaptcha` and you're good to go.

I have the full intention of keeping the old namespace for at least the 4.x versions.

~~@Scyllaly I'm more than happy to submit the changes back to you if you so wish, on the condition that I'm made maintainer of this repo.~~

**Comment by tfevan** [comment]
> 

Thank you. Just updated :)

**Comment by RVxLab** [comment]
My fork has just released version 5.x with a major code modernization. [Check it out](https://github.com/RVxLab/hcaptcha/tree/5.0.0)!

**Comment by Scyllaly** [comment]
@RVxLab @tfevan   I have been merged this PR : https://github.com/Scyllaly/hcaptcha/pull/8
check it.

**Comment by RVxLab** [comment]
Good to know that Laravel 9 is now supported. However since it took 2 months to land and my fork contains extra features such as blade component support I will keep maintaining that.
